---
title: "Assignment 6"
author: "Lamei Zhang"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
library(leaflet)
library(sf)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(ggspatial)
library(htmlwidgets)
library(tidytransit)
```

```{r, r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
Middlesex_White <- get_decennial(geography = "block",
                          state = "MA", county = "Middlesex",
                          year = 2010,
                          output = "wide",
                          variables = c(tot_pop = 'P008001',
                                        white_pop = 'P005003'),
                          geometry = TRUE)

Middlesex_Hispanic <- get_decennial(geography = "block",
                                    state = "MA", county = "Middlesex",
                                    year = 2010,
                                    output = "wide",
                                    variables = c(tot_pop = 'P008001',
                                                  his_pop = 'P009002'),
                                    geometry = TRUE)
```


```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
Middlesex_White <- Middlesex_White %>%
  mutate(pct_white = white_pop / tot_pop) %>%
  filter(tot_pop > 0)

Middlesex_Hispanic <- Middlesex_Hispanic %>%
  mutate(pct_his = his_pop / tot_pop) %>%
  filter(tot_pop > 0)

```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
MA_state_plane <- "+proj=lcc +lat_1=42.68333333333333 +lat_2=41.71666666666667 +lat_0=41 +lon_0=-71.5 +x_0=200000.0001016002 +y_0=750000 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs"
```


```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
ggplot(Middlesex_White) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw") +
  geom_sf(color = NA, aes(fill = pct_white), alpha = 0.7) +
  coord_sf(crs = MA_state_plane) +
  scale_fill_gradient2(low = "green", mid = "yellow", high = "red", midpoint = .5,
                       name = "Percent of population\nidentifying as White",
                       breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1),
                       labels = c("0%", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%")) +
  theme_void()
```


```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
ggplot(Middlesex_Hispanic) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw") +
  geom_sf(color = NA, aes(fill = pct_his), alpha = 0.7) +
  coord_sf(crs = MA_state_plane) +
  scale_fill_continuous(low="blue", high="yellow",
                      na.value = NA, 
                       name = "Percent of population\nidentifying as Hispanic",
                       breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1),
                       labels = c("0%", "20%", "40%", "60%", "80%", "100%")) +
  theme_void() 

```
```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}

MA_White_palette <- colorNumeric(c("green", "red"), Middlesex_White$pct_white)

White_map1 <- leaflet(Middlesex_White) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(stroke = FALSE, fillOpacity = 0.7,
    color = ~MA_White_palette(pct_white)) %>%
  addLegend("bottomright", pal = MA_White_palette, values = ~pct_white,
    title = "Percent of population<br/>identifying as White alone",
    labFormat = labelFormat(suffix = "%",
                            transform = function(x) 100 * x),
    opacity = 1)

White_map1

```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}

White_map2 <- leaflet(Middlesex_White) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(color = ~MA_White_palette(pct_white), stroke = FALSE, fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "darkorange", fillOpacity = 0.9),
              label = "This is a label",
              popup = "This is a popup") %>%
    addLegend("bottomright", pal = MA_White_palette, values = ~pct_white,
    title = "Percent of population<br/>identifying as Black alone",
    labFormat = labelFormat(suffix = "%",
                            transform = function(x) 100 * x),
    opacity = 1)

White_map2

```

```{r, message = FALSE, warning = FALSE, echo = FALSE}

White_map3 <- leaflet(Middlesex_White) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(color = ~MA_White_palette(pct_white), stroke = FALSE, fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "darkorange", fillOpacity = 0.9),
              label = Middlesex_White$NAME,
              popup = paste("Total population: ", Middlesex_White$tot_pop, "<br/>",
                            "White (non-Hispanic) population: ", Middlesex_White$bl_pop, " (", 
                            round(Middlesex_White$pct_white * 100, 1), "%)", sep = "")) %>%
    addLegend("bottomright", pal = MA_White_palette, values = ~pct_white,
    title = "Percent of population<br/>identifying as White alone",
    labFormat = labelFormat(suffix = "%",
                            transform = function(x) 100 * x),
    opacity = 1)

White_map3

```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}

saveWidget(White_map3, file="inter_white.html")

```

### Interactive Maps with ACS data

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
transit_Middlesex <- get_acs(geography = "tract", county = "Middlesex", state = "MA", 
                           year = 2019, survey = "acs5",
                           variables = c(tot_wrkrs = "B08301_001", pt_wrkrs = "B08301_010"),
                           output = "wide", geometry = TRUE) 

```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}

transit_Middlesex <- transit_Middlesex %>%
  select(-tot_wrkrsM, -pt_wrkrsM) %>%
  filter(tot_wrkrsE > 0) %>%
  mutate(pct_transit = round(100 * pt_wrkrsE / tot_wrkrsE, 1))

```
```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
transit_palette <- colorNumeric(c("pink", "lightblue"),
                                transit_Middlesex$pct_transit)

transit_map <- leaflet(transit_Middlesex) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(fillColor = ~transit_palette(pct_transit), weight = 1, color = "gray", fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "yellow", fillOpacity = 0.9),
              label = transit_Middlesex$NAME,
              popup = paste("Total workers: ", transit_Middlesex$tot_wrkrsE, "<br/>",
                            "Transit commuters: ", transit_Middlesex$pt_wrkrsE, " (", 
                            transit_Middlesex$pct_transit, "%)", sep = "")) %>%
    addLegend("bottomright", pal = transit_palette, values = ~pct_transit,
    title = "Percent of workers<br/>communting by transit",
    labFormat = labelFormat(suffix = "%"),
    opacity = 1)

transit_map

```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}

MBTA_url <- feedlist[feedlist$t == "MBTA GTFS",]$url_d

MBTA <- read_gtfs(MBTA_url)

transit_stops <- MBTA$stops

transit_stations <- transit_stops %>%
  filter(location_type == 1)

```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
station_sf <- st_as_sf(transit_stations, 
                          coords = c("stop_lon", "stop_lat"), 
                          crs = "WGS84")

st_write(station_sf, "MBTA_stations.csv", layer_options = "GEOMETRY=AS_XY", append = FALSE)

stations_2 <- read_csv("MBTA_stations.csv")
```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
transit_map2 <- transit_map %>%
  addMarkers(lng = transit_stations$stop_lon,
             lat = transit_stations$stop_lat,
             popup = transit_stations$stop_name)

transit_map2

```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}
limits <- st_bbox(transit_Middlesex)

transit_map3 <- transit_map2 %>%
   fitBounds( lng1 = as.numeric(limits[1]),
                lat1 = as.numeric(limits[2]),
                lng2 = as.numeric(limits[3]),
                lat2 = as.numeric(limits[4])) %>%
   setMaxBounds( lng1 = as.numeric(limits[1]),
                lat1 = as.numeric(limits[2]),
                lng2 = as.numeric(limits[3]),
                lat2 = as.numeric(limits[4])) 

transit_map3

```

```{r, message = FALSE, warning = FALSE, echo = FALSE, results = FALSE}

transit_map4 <- transit_map %>%
  addCircleMarkers(stroke = FALSE, color = "black", fillOpacity = 1, radius = 3,
                   lng = transit_stations$stop_lon,
                   lat = transit_stations$stop_lat,
                   popup = transit_stations$stop_name) %>%
   fitBounds( lng1 = as.numeric(limits[1]),
                lat1 = as.numeric(limits[2]),
                lng2 = as.numeric(limits[3]),
                lat2 = as.numeric(limits[4])) %>%
   setMaxBounds( lng1 = as.numeric(limits[1]),
                lat1 = as.numeric(limits[2]),
                lng2 = as.numeric(limits[3]),
                lat2 = as.numeric(limits[4])) 

transit_map4

```

